### ISSUE TITLE
Segfault on Ubuntu 22.04

### ISSUE THREAD

**Issue by GabrielCNoble** [Mr-Wiseguy/Zelda64Recomp#28]
**Describe the bug**
When trying to launch it, the window pops open and then it segfaults. Gdb shows it's crashing inside XQueryExtension.

**To Reproduce**
Just launch it.

**Expected behavior**
No segfault.

**Screenshots**
![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/16003370/d89d2c3d-5dc1-46eb-b282-853553b91f11)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Version: 1.0.0
 - CPU: Intel Core i5-8265U
 - GPU: Intel UHD 620

**Comment by Mr-Wiseguy** [comment]
Thanks for the bug report. A crash in XQueryExtension is odd, and may mean I need to make a flatpak or appimage version for better distro support. Alternatively, once I finish the build instructions you may have better luck with a version built directly on your machine. In the meantime, are you able to run the Windows version through Proton?

**Comment by FoxbitDreamtail** [comment]
Fun fact you can actually run this through wine, specifically the wine staging build, that's what I'm running it through and it works like a charm, people oftentimes forget that wine is the original Windows compatibility layer and it's still getting updated, so yeah whenever possible I recommend using wine as it has full system integration then using proton which you need to use through an app.

**Comment by GabrielCNoble** [comment]
Tried running it through Proton. It launches and seems to run fine, but the image freezes. Tried Proton 9.0-1 and experimental through Steam. Same thing happens with Wine 9.0. I'll give wine's staging build a try.

**Comment by Mr-Wiseguy** [comment]
That issue with proton/wine may be the known issue that's listed in the readme for Intel integrated GPUs on Linux. Recomp automatically detects when being run under proton or wine and switches to Vulkan, which lets the runtime just pass the graphics calls through directly to the driver. Unfortunately, we don't know the root cause of the issue yet so it may be some time before it's fixed. Sorry about that.

**Comment by nadiaholmquist** [comment]
I seem to have this issue on Fedora 40 with KDE Wayland as well. Though on my end the crash happens in `wl_display_interface` as apparently called by `XQueryExtension`.

For now this can be worked around by using gamescope, like `gamescope -f ./Zelda64Recompiled`, though you need to manually change the `wm_option` setting to `Fullscreen` in `~/.config/Zelda64Recompiled/graphics.json` to get the game to render at the correct resolution, trying to set it in-game won't work.

**Comment by Lachrymogenic** [comment]
I'm getting the same error on Ubuntu, got this message in dmesg, if it helps:
`[ 6740.060189] Gfx Thread[27040]: segfault at 969 ip 00007fb7b0555e44 sp 00007fb775bfaca0 error 4 in libX11.so.6.4.0[7fb7b0539000+8b000] likely on CPU 2 (core 2, socket 0)
`
`
[ 6740.060202] Code: 48 89 44 24 28 31 c0 48 85 f6 0f 84 e6 00 00 00 48 89 f7 e8 6e 3c fe ff 49 89 c0 31 c0 49 81 f8 fe ff 00 00 0f 87 a3 00 00 00 <48> 8b 85 68 09 00 00 48 85 c0 74 05 48 89 ef ff 10 ba 08 00 00 00
`

Can confirm I get the exact same error with gdb

**Comment by EibrielInv** [comment]
Also getting segfault on Ubuntu 22.04.4 LTS, but running perfectly on Proton Experimental for me

OS: Ubuntu 22.04.4 LTS
KERNEL: 5.15.0-84-generic
CPU: 12th Gen Intel Core i3-12100F
GPU: NVIDIA GeForce GTX 1080 Ti
GPU DRIVER: NVIDIA 535.104.05
RAM: 32 GB

**Comment by mexerica** [comment]
I am getting the same problem on Linux Mint 21.3 Cinnamon.

OS: Linux Mint 21.3 Cinnamon.
KERNEL: 5.15.0-105-generic
CPU: Intel Core i5-2310
RAM: 16 GB

**Comment by vgmoose** [comment]
I was also on Ubuntu 22.04 and hitting this same error (even the same XQueryExtension crash in gdb), but now updated to 23.10 and the game is running!

**Comment by Micolithe** [comment]
I'm also having this same issue. Running it in GDB I get the same error about XQueryExtension.

I'm on:
OS- Linux Mint 21.1 Cinnamon
Kernel- 5.15.0-105-generic
CPU- AMD Ryzen 5 5600 (12) @ 3.500GHz
Video Card- NVIDIA GeForce RTX 2060 SUPER
Video Drivers- Nvidia 535.171.04
RAM- 64GB

**Comment by GabrielCNoble** [comment]
Alright, building it from source worked flawlessly. You guys did a killer job in making it easy, congrats.

I had to set the game to 2x original resolution. Setting it to auto causes the same freezing issue as before, and this time it spammed vulkan errors

![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/16003370/acc078d0-fc19-4a09-90ba-51870be6b450)

Also, for some reason, trying to disable anti-aliasing caused the game to hang. It also spit this error when it happened

![image](https://github.com/Mr-Wiseguy/Zelda64Recomp/assets/16003370/7e840d82-88fe-465e-9c09-dc2151d1fe03)

It doesn't seem to be happening anymore, though.

**Comment by kinzaye** [comment]
It's sort of been answered in another issue but because this is the first one I came across when searching, the seg fault seems to be caused by Wayland. As a work around you can launch the game by running ```WAYLAND_DISPLAY="" ./Zelda64Recompiled``` to force it to use Xwayland instead OR log into your desktop environment in Xorg mode! :smile:

**Comment by FoxbitDreamtail** [comment]
So ironically, when I was using mint which is based on Ubuntu, it still uses x11 and because it uses x11 it's still perplexes me when it crashed.

**Comment by GabrielCNoble** [comment]
Version 1.1.1 worked flawlessly out of the box.

**Comment by Mr-Wiseguy** [comment]
That's interesting, are you still using the same Intel integrated GPU? No progress has been made towards fixing the Intel iGPU issue, so if it's working now then some seemingly unrelated change somehow fixed it.

**Comment by GabrielCNoble** [comment]
Yep, same integrated GPU. Hmm, I just remembered something... I updated my machine a couple of days ago. Maybe that fixed it?

**Comment by Mr-Wiseguy** [comment]
If the latest drivers fixed this issue then that's great to hear! I'll be able to verify if that's the case on my own Intel laptop in a few days, so thanks for the heads up.

**Comment by Mr-Wiseguy** [comment]
I finally got my laptop back and tested on the intel iGPU, but even after installing Mesa 24.1.1 via a PPA I'm still getting the vkQueueSubmit/vkWaitForFences error. Can you show the result of `vulkaninfo --summary`? Maybe I can spot a difference there that will explain how it's working for you.

**Comment by GabrielCNoble** [comment]
```
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Failed to CreateInstance in ICD 2.  Skipping ICD.
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Failed to CreateInstance in ICD 5.  Skipping ICD.
==========
VULKANINFO
==========

Vulkan Instance Version: 1.3.204


Instance Extensions: count = 21
-------------------------------
VK_EXT_acquire_drm_display             : extension revision 1
VK_EXT_acquire_xlib_display            : extension revision 1
VK_EXT_debug_report                    : extension revision 10
VK_EXT_debug_utils                     : extension revision 2
VK_EXT_direct_mode_display             : extension revision 1
VK_EXT_display_surface_counter         : extension revision 1
VK_EXT_headless_surface                : extension revision 1
VK_EXT_swapchain_colorspace            : extension revision 4
VK_KHR_device_group_creation           : extension revision 1
VK_KHR_display                         : extension revision 23
VK_KHR_external_fence_capabilities     : extension revision 1
VK_KHR_external_memory_capabilities    : extension revision 1
VK_KHR_external_semaphore_capabilities : extension revision 1
VK_KHR_get_display_properties2         : extension revision 1
VK_KHR_get_physical_device_properties2 : extension revision 2
VK_KHR_get_surface_capabilities2       : extension revision 1
VK_KHR_surface                         : extension revision 25
VK_KHR_surface_protected_capabilities  : extension revision 1
VK_KHR_wayland_surface                 : extension revision 6
VK_KHR_xcb_surface                     : extension revision 6
VK_KHR_xlib_surface                    : extension revision 6

Instance Layers: count = 7
--------------------------
VK_LAYER_INTEL_nullhw             INTEL NULL HW                1.1.73   version 1
VK_LAYER_MESA_device_select       Linux device selection layer 1.3.211  version 1
VK_LAYER_MESA_overlay             Mesa Overlay layer           1.3.211  version 1
VK_LAYER_VALVE_steam_fossilize_32 Steam Pipeline Caching Layer 1.3.207  version 1
VK_LAYER_VALVE_steam_fossilize_64 Steam Pipeline Caching Layer 1.3.207  version 1
VK_LAYER_VALVE_steam_overlay_32   Steam Overlay Layer          1.3.207  version 1
VK_LAYER_VALVE_steam_overlay_64   Steam Overlay Layer          1.3.207  version 1

Devices:
========
GPU0:
	apiVersion         = 4206877 (1.3.285)
	driverVersion      = 100671488 (0x6002000)
	vendorID           = 0x8086
	deviceID           = 0x3ea0
	deviceType         = PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
	deviceName         = Intel(R) UHD Graphics 620 (WHL GT2)
	driverID           = DRIVER_ID_INTEL_OPEN_SOURCE_MESA
	driverName         = Intel open-source Mesa driver
	driverInfo         = Mesa 24.2~git2405300600.c1d3fa~oibaf~j (git-c1d3fa0 2024-05-30 jammy-oibaf-ppa)
	conformanceVersion = 1.3.6.0
	deviceUUID         = 8680a03e-0200-0000-0002-000000000000
	driverUUID         = 5048dd2b-3087-c91b-bb71-1829f61c1674
GPU1:
	apiVersion         = 4206877 (1.3.285)
	driverVersion      = 1 (0x0001)
	vendorID           = 0x10005
	deviceID           = 0x0000
	deviceType         = PHYSICAL_DEVICE_TYPE_CPU
	deviceName         = llvmpipe (LLVM 15.0.7, 256 bits)
	driverID           = DRIVER_ID_MESA_LLVMPIPE
	driverName         = llvmpipe
	driverInfo         = Mesa 24.2~git2405300600.c1d3fa~oibaf~j (git-c1d3fa0 2024-05-30 jammy-oibaf-ppa) (LLVM 15.0.7)
	conformanceVersion = 1.3.1.1
	deviceUUID         = 6d657361-3234-2e32-7e67-697432343000
	driverUUID         = 6c6c766d-7069-7065-5555-494400000000
```

**Comment by GabrielCNoble** [comment]
I may have jumped the gun when I said it worked flawlessly. When I set MS multisampling to 4x, I also get a bunch of vkWaitForFences and vkQueueSubmit errors, followed by a SIGABRT.

```
vkWaitForFences failed with error code 0xFFFFFFFC.
vkWaitForFences failed with error code 0xFFFFFFFC.
vkWaitForFences failed with error code 0xFFFFFFFC.
vkQueueSubmit failed with error code 0xFFFFFFFC.
vkWaitForFences failed with error code 0xFFFFFFFC.
vkQueueSubmit failed with error code 0xFFFFFFFC.
vkWaitForFences failed with error code 0xFFFFFFFC.
Zelda64Recompiled: /home/gabriel/Documents/Compiler/Zelda64Recomp/lib/rt64/src/vulkan/rt64_vulkan.cpp:3165: virtual void RT64::VulkanCommandQueue::executeCommandLists(const RenderCommandList **, uint32_t, RenderCommandFence *): Assertion `swapChain->acquireNextTextureSemaphoreSignaled' failed.
vkQueueSubmit failed with error code 0xFFFFFFFC.
vkWaitForFences failed with error code 0xFFFFFFFC.
vkQueueSubmit failed with error code 0xFFFFFFFC.
vkWaitForFences failed with error code 0xFFFFFFFC.
vkQueueSubmit failed with error code 0xFFFFFFFC.
vkWaitForFences failed with error code 0xFFFFFFFC.
vkQueueSubmit failed with error code 0xFFFFFFFC.
vkWaitForFences failed with error code 0xFFFFFFFC.
vkQueueSubmit failed with error code 0xFFFFFFFC.
vkWaitForFences failed with error code 0xFFFFFFFC.
vkQueueSubmit failed with error code 0xFFFFFFFC.
vkWaitForFences failed with error code 0xFFFFFFFC.
vkQueueSubmit failed with error code 0xFFFFFFFC.
vkWaitForFences failed with error code 0xFFFFFFFC.
vkQueueSubmit failed with error code 0xFFFFFFFC.
vkWaitForFences failed with error code 0xFFFFFFFC.
vkQueueSubmit failed with error code 0xFFFFFFFC.
vkWaitForFences failed with error code 0xFFFFFFFC.
vkQueueSubmit failed with error code 0xFFFFFFFC.
vkWaitForFences failed with error code 0xFFFFFFFC.
vkQueueSubmit failed with error code 0xFFFFFFFC.
vkWaitForFences failed with error code 0xFFFFFFFC.
vkQueueSubmit failed with error code 0xFFFFFFFC.
vkWaitForFences failed with error code 0xFFFFFFFC.
vkQueueSubmit failed with error code 0xFFFFFFFC.
vkWaitForFences failed with error code 0xFFFFFFFC.

Thread 36 "RT64 Present" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff86ffd640 (LWP 164792)]
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140735458301504) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140735458301504) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140735458301504) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140735458301504, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff6642476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff66287f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff662871b in __assert_fail_base (fmt=0x7ffff67dd130 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x5555587fc046 "swapChain->acquireNextTextureSemaphoreSignaled", 
    file=0x5555587f96db "/home/gabriel/Documents/Compiler/Zelda64Recomp/lib/rt64/src/vulkan/rt64_vulkan.cpp", line=3165, function=<optimized out>) at ./assert/assert.c:92
#6  0x00007ffff6639e96 in __GI___assert_fail (assertion=0x5555587fc046 "swapChain->acquireNextTextureSemaphoreSignaled", 
    file=0x5555587f96db "/home/gabriel/Documents/Compiler/Zelda64Recomp/lib/rt64/src/vulkan/rt64_vulkan.cpp", line=3165, 
    function=0x5555587fbf9f "virtual void RT64::VulkanCommandQueue::executeCommandLists(const RenderCommandList **, uint32_t, RenderCommandFence *)") at ./assert/assert.c:101
#7  0x0000555557f57623 in RT64::VulkanCommandQueue::executeCommandLists (this=0x7fffc8f8e080, commandLists=0x7fff86ffbc10, commandListCount=1, signalFence=0x7fffc8f8e3f0)
    at /home/gabriel/Documents/Compiler/Zelda64Recomp/lib/rt64/src/vulkan/rt64_vulkan.cpp:3165
#8  0x0000555557ed22db in RT64::RenderCommandQueue::executeCommandLists (this=0x7fffc8f8e080, commandLists=0x7fffc8f8e100, signalFence=0x7fffc8f8e3f0)
    at /home/gabriel/Documents/Compiler/Zelda64Recomp/lib/rt64/src/rhi/rt64_render_interface.h:180
#9  0x0000555557ed1f2f in RT64::RenderWorker::execute (this=0x7fffc8f8e030) at /home/gabriel/Documents/Compiler/Zelda64Recomp/lib/rt64/src/render/rt64_render_worker.cpp:24
#10 0x0000555557e34213 in RT64::PresentQueue::threadPresent (this=0x7fffc90832c0, present=...) at /home/gabriel/Documents/Compiler/Zelda64Recomp/lib/rt64/src/hle/rt64_present_queue.cpp:357
#11 0x0000555557e32afd in RT64::PresentQueue::threadLoop (this=0x7fffc90832c0) at /home/gabriel/Documents/Compiler/Zelda64Recomp/lib/rt64/src/hle/rt64_present_queue.cpp:493
#12 0x0000555557e362f9 in std::__invoke_impl<void, void (RT64::PresentQueue::*)(), RT64::PresentQueue*> (
    __f=@0x7fffc907e4a0: (void (RT64::PresentQueue::*)(RT64::PresentQueue * const)) 0x555557e32530 <RT64::PresentQueue::threadLoop()>, __t=@0x7fffc907e498: 0x7fffc90832c0)
    at /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:74
#13 0x0000555557e3623d in std::__invoke<void (RT64::PresentQueue::*)(), RT64::PresentQueue*> (
    __fn=@0x7fffc907e4a0: (void (RT64::PresentQueue::*)(RT64::PresentQueue * const)) 0x555557e32530 <RT64::PresentQueue::threadLoop()>, __args=@0x7fffc907e498: 0x7fffc90832c0)
    at /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:96
#14 0x0000555557e36212 in std::thread::_Invoker<std::tuple<void (RT64::PresentQueue::*)(), RT64::PresentQueue*> >::_M_invoke<0ul, 1ul> (this=0x7fffc907e498)
    at /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_thread.h:259
#15 0x0000555557e361d5 in std::thread::_Invoker<std::tuple<void (RT64::PresentQueue::*)(), RT64::PresentQueue*> >::operator() (this=0x7fffc907e498)
    at /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_thread.h:266
#16 0x0000555557e360b9 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (RT64::PresentQueue::*)(), RT64::PresentQueue*> > >::_M_run (this=0x7fffc907e490)
    at /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_thread.h:211
#17 0x00005555586fbea4 in execute_native_thread_routine ()
#18 0x00007ffff6694ac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#19 0x00007ffff6726850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

**Comment by Mr-Wiseguy** [comment]
Aha, that seems to be the missing piece of the puzzle. By turning off MSAA I was able to get recomp running on my laptop's Intel iGPU even after reverting to the Mesa version that kubuntu 24.04 normally has (24.0.5). This means that the driver bug is most likely related to MSAA sample positions, which is a niche feature that RT64 uses to avoid artifacts in texture sampling when MSAA is enabled.

All in all, it looks like recomp should have no issue running on Intel Mesa as long as the driver is sufficiently up-to-date and MSAA is disabled. Maybe we'll force MSAA off if Intel Mesa is detected in a future update.

**Comment by Phantop** [comment]
I'm bumping into this even without MSAA on Arch using the latest release build (Intel i5-1135G7 w/ Xe graphics, Mesa 25.1.1-2, X11 if that's somehow relevant). Seems to happen regardless of graphical settings and pretty easily reproducible just by waiting around on the title screen for a bit. Don't seem to get a segfault but I get a hang (~10 seconds) and then the game continues with frozen visuals and log spam of:
```
vkWaitForFences failed with error code 0xFFFFFFFC.
vkQueueSubmit failed with error code 0xFFFFFFFC.
```
